sudo: false
language: python
matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
# Disabling 3.3 pending https://github.com/awslabs/base64io-python/issues/4
#    - python: 3.3
#      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=mypy-py2
    - python: 3.6
      env: TOXENV=mypy-py3
    - python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
install: pip install tox
script: tox
